FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# users

## Question [/corsi/{question_id}]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
           "id":1,2,3 
        }

+ Response 201 (application/json)

    + Headers

            Location: /corsi/1

    + Body

            {
                [
                    {
                        "id": 1,
                        "title": "Corso specializzato polmoni",
                        "description": "AAA",
                        "date": "15/09/2018",
                        "hour": "10/16",
                        "ecm": "ECM Toscana",
                        "city": "Arezzo",
                        "cost": "10"
                    },
                    {
                        "id": 2,
                        "title": "Corso specializzato cuore",
                        "description": "BBB",
                        "date": "13/10/2018",
                        "hour": "9/15",
                        "ecm": "ECM Toscana",
                        "city": "Firenze",
                        "cost": "12"
                      },
                      {
                        "id": 3,
                        "title": "Corso specializzato mani",
                        "description": "CCC",
                        "date": "03/11/2018",
                        "hour": "12/17",
                        "ecm": "ECM Toscana",
                        "city": "Pisa",
                        "cost": "15"
                      }
                ]
            }