FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# corsi

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/user]

### List All user [GET]

+ Response 200 (application/xml)

        <tag>
            <user>fdffggf</user>
        </tag>