FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# PROVA

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/corsi]

### Question corsi[POST]

Puoi utilizzare questa richiesta per ottenere l'elenco di tutti i corsi!

+ Request (application/json)

        {
            "choices": [
               1,
               2,
               3
            ]
        }

+ Response 200 (application/json)

    + Headers

            Location: /corsi

    + Body

            {

                "choices": [
                              {
                                "id": 1,
                                "title": "Corso specializzato polmoni",
                                "description": "AAA",
                                "date": "15/09/2018",
                                "hour": "10/16",
                                "ecm": "ECM Toscana",
                                "city": "Arezzo",
                                "cost": "10"
                              },
                              {
                                "id": 2,
                                "title": "Corso specializzato cuore",
                                "description": "BBB",
                                "date": "13/10/2018",
                                "hour": "9/15",
                                "ecm": "ECM Toscana",
                                "city": "Firenze",
                                "cost": "12"
                              },
                              {
                                "id": 3,
                                "title": "Corso specializzato mani",
                                "description": "CCC",
                                "date": "03/11/2018",
                                "hour": "12/17",
                                "ecm": "ECM Toscana",
                                "city": "Pisa",
                                "cost": "15"
                              }
                              ]
            }
            

## Questions Collection [/dettaglioCorsi]

### Question dettaglio corsi [POST]

Puoi utilizzare questa richiesta per ottenere il dettaglio dei corsi!

+ Request (application/json)

        {
            
        }

+ Response 200 (application/json)

    + Headers

            Location: /dettaglioCorsi

    + Body

            {
                "id": 1,
                "title": "Corso specializzato polmoni",
                "description": "AAA",
                "date": "15/09/2018",
                "hour": "10/16",
                "ecm": "ECM Toscana",
                "city": "Arezzo",
                "cost": "10",
                "dettaglio":"Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
            }
                              
            
            

## Questions Collection [/Profilo]

### Question dettaglio profilo [POST]

Puoi utilizzare questa richiesta per ottenere i dati del profilo utente!

+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /profilo

    + Body

            {
                "titoloProfilo":"Profilo Utente",
                "nome":"Mario",
                "cognome":"Rossi",
                "email":"mariorossi@email.it",
                "professione":"medico",
                "codicefiscale_piva":"CODICEFISCALEQWERTY",
                "indirizzo":"Viale Glorioso, 45 - 00153 Roma",
                "titoloWallet":"Wallet",
                "gettonidisponibili":20,
                

                              
            }
            


## Questions Collection [/acquistoGettoni]

### Question acquisto gettoni [POST]

Puoi utilizzare questa richiesta per iniziare l'acquisto dei gettoni

+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /acquistoGettoni

    + Body

            {
                "titoloConferma":"Conferma di acquisto di $ gettoni",
                "sottotitolo":"Gentile X Y, ha acquistato correttamente i suoi gettoni virtuali.",
                "totaleOrdine":"Totale ordine: ",
                "numeroOrdine":"Numero ordine: ",
                "nuovoSaldoGettoni":"Nuovo saldo gettoni: ",
                "descrizione":"Riceverai i dettagli dell'ordine e la fattura direttamente via email, all'indirizzo: "
                              
            }


## Questions Collection [/pagamento]

### Question pagamento [POST]

Puoi utilizzare questa richiesta per pagare i gettoni

+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /pagamento

    + Body

            {
                "titoloPaypal":"PAYPAL",
                "titoloCartaDiCredito":"Carta di credito",
                "titoloBonifico":"Acquisto di $ gettoni con Bonifico Bancario",
                "nome":"Mario",
                "cognome":"Rossi",
                "email":"mariorossi@email.it",
                "professione":"medico",
                "codicefiscale_piva":"CODICEFISCALEQWERTY",
                "indirizzo":"Viale Glorioso, 45 - 00153 Roma",
                "gettonidisponibili":20,
                "banca":"Intesa San Paolo",
                "IBAN":"ibanibaniban",
                "causale":"Ordine n",
                "descrizione":"Riceverai i dettagli dell'ordine e gli estremi per il bonifico direttamente via email, all'indirizzo: email"

            }

## Questions Collection [/confermaPagamento]

### Question conferma pagamento[POST]

Puoi utilizzare questa richiesta per confermare il pagamento dei gettoni

+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /confermaPagamento

    + Body

            {
                "titoloConferma":"Conferma di acquisto di $ gettoni",
                "sottotitolo":"Gentile X Y, ha acquistato i suoi gettoni virtuali",
                "totaleOrdine":"$",
                "numeroOrdine":"1232242L",
                "nuovoSaldoGettoni":"$",
                "descrizione":"Riceverai i dettagli dell'ordine e la fattura direttamente via email, all'indirizzo: "
            }
            
            
## Questions Collection [/corsiPrenotati]

### Question corsi prenotati [POST]

Puoi utilizzare questa richiesta per controllare i corsi prenotati

+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /corsiPrenotati

    + Body

            {
                "titolo":"Prossimi corsi prenotati",
                "titoloCorso":"Corso specializzato polmoni",
                "località":"Arezzo",
                "Organizzatore":"ECM Toscana",
                "data":"15 Settembre 2018",
                "orario":"10/16",
                "crediti":"Crediti ECM: n"
            };
             {
                "titolo":"Prossimi corsi prenotati",
                "titoloCorso":"Sutura chirurgica. Dalla teoria alla pratica",
                "località":"Milano",
                "Organizzatore":"Pegaso Formazione",
                "data":"25 Settembre 2018",
                "orario":"10/16",
                "crediti":"Crediti ECM: n"
            }
            
            
## Questions Collection [/questionario]

### Question questionario [POST]

Puoi utilizzare questa richiesta per compilare il questionario

+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /questionario

    + Body

            {
                "titoloCorso":"Corso specializzato polmoni",
                "località":"Arezzo",
                "Organizzatore":"ECM Toscana",
                "data":"15 Settembre 2018",
                "orario":"10/16",
                "crediti":"Crediti ECM: n",
                "domanda1":"Quale dosaggio si consiglia per un caso di malessere? 0,25mg",
                "domanda2":"Quale dosaggio si consiglia per un caso di malessere? 0,25mg",
                "domanda3":"Quale dosaggio si consiglia per un caso di malessere? 0,25mg",
                "domanda4":"Quale dosaggio si consiglia per un caso di malessere? 0,25mg"

            }
            
## Questions Collection [/valutazioneQualità]

### Question valutazioneQualità [POST]

Puoi utilizzare questa richiesta per valutare la qualità del corso/docente

+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /valutazioneQualità

    + Body

            {
                "titolo":"Valutazione qualità",
                "sottotitolo":"In questa schermata può valutare la qualità del corso frequentato.",
                "titoloPreparazioneDocente":"Preparazione del docente"
            }
            
            
## Questions Collection [/questionarioCompletato]

### Question questionarioCompletato [POST]

Puoi utilizzare questa richiesta per la vista del questionario completato

+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /questionarioCompletato

    + Body

            {
                "titolo":"Questionario completato",
                "sottotitolo":"Gentili X Y, ha correttamente completato il questionario.",
                "titoloCorso":"Corso specializzato polmoni",
                "località":"Arezzo",
                "Organizzatore":"ECM Toscana",
                "data":"15 Settembre 2018",
                "orario":"10/16",
                "crediti":"Crediti ECM: n"
            }
            

## Questions Collection [/verificaQuestionario]

### Question verificaQuestionario [POST]

Puoi utilizzare questa richiesta per la verifica: i presenti in aula stanno compilando il questionario.

+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /verificaQuestionario

    + Body

            {
                "titolo":"Verifica in corso",
                "sottotitolo":"I presenti in aula verificati stanno compilando il questionario.",
                "minutiRimanenti":"X minuti rimanenti"
                
            }
            
## Questions Collection [/proceduraDiAccreditoPresentiInAula]

### Question proceduraDiAccreditoPresentiInAula [POST]

Puoi utilizzare questa richiesta per lanciare la procedura di accredito automatico dei presenti in aula.
+ Request (application/json)

        {
           
        }

+ Response 200 (application/json)

    + Headers

            Location: /proceduraDiAccreditoPresentiInAula

    + Body

            {
                "titolo":"Procedura di accredito",
                "sottotitolo":"Stai per lanciare la procedura di accredito automatico dei presenti in aula.",
                "dispositivoDiVerifica":"Dispositivo di verifica: BEACON_TOSCANA_01"
                
            }