FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# users

{
  "id": 1,
  "name": "student1@gmail.com",
  "roles": [
    "ROLE_STUDENT"
  ],
  "nickName": "Student Imprudent",
  "picture": "/../assets/images/default_session_image.png",
  "registrationDate": 1533651178420
}
